### PR TITLE
Add hpe-components-1.0 - Adobe XD

### PR DESCRIPTION
**Pull request by JetLim**
Create hpe-components-1.0 for Adobe XD

### CODE REVIEW

**Comment by L0ZZI** [comment]
Hey man, it looks like the export from Sketch to XD is clean from a layer view perspective, but the symbols and responsiveness is more of a problem as shown in the attached screenshot. 

screen shot 2017-07-31 at 2 06 57 pm

I would say that we need to simplify the export or just let it be. I would like to open it up to the group @tracybarmore @gbr @dgennetten @harishcoorg to decide how much support we throw towards XD (if any) as there are other issues with no support for text or color styles, limited drawing tools, and lack of extensibility...Anyone?

**Comment by JetLim** [comment]
To export Sketch to XD is not as straight forward as it appears to be. To enable XD to import the Sketch elements, export it to SVG (I did it part by part making sure everything are in order and not exporting it as an entire art board). 

Here is the highlight of the process, :) ,... after importing the element into XD,  the fixes needed on the elements includes element alignments, element folder and labels clean up, and making any icon element to a symbol in XD. Let's talk more about it tomorrow. I think I might have something to solve for the responsiveness of it.

**Comment by L0ZZI** [comment]
Thanks Jet! I'm going to close the two XD PR's and then I think it would be a good exercise to write grommet blog post as @tracybarmore mentioned to tell what the finding were and we should link the resulting files for people to inspect.

**Comment by L0ZZI** [comment]
As mentioned in pr84 we close the Adobe XD sticker sheet translations. Thanks for the work on this.

**Comment by L0ZZI** [comment]
As mentioned in #84 we close the Adobe XD sticker sheet translations. Thanks for the work on this.

**Pull request closed without merging**
