### PR TITLE
Adding two functional icons: tape and erase

### PR DESCRIPTION
**Pull request by dgennetten**

### CODE REVIEW

**Comment by L0ZZI** [comment]
Thanks for submitting this. The icons need more refinement before I merge (paths need to be on whole pixels and all shapes need to be compounded) but the art looks good! :-) See attached. Let me know if you have any questions on how to make the changes and or why I've done them.

As for the app icons, what you did is fine, but going forward you can break the app-icons into specific products/team files "hpe-design/hpe-app-icons/hpe-avenger-app-icon-01.sketch", I want to start breaking up that file—right now it's a mess (my bad).
[icon-tweaks.zip](https://github.com/grommet/grommet-design/files/1188809/icon-tweaks.zip)

**Comment by dgennetten** [comment]
@L0ZZI I repaired the non-integer nodes. Thx.

**Comment by dgennetten** [comment]
@L0ZZI ,  What is the sequence of events between this PR and a released icon that the vdu team can use?

**Comment by L0ZZI** [comment]
they can pull updates from, https://github.com/grommet/grommet-icon-loader

**Pull request merged**
